[package]
name = "tokiopreme"
version = "0.1.0"
authors = ["raakka <xvi@xvisolutions.xyz>"]
edition = "2018"

[dependencies]
tokio = { version = "1.2.0", features = ["full"] }
reqwest = "0.11.1"

[[bin]]
name = "tokiopreme"
